version: '3.7'
services:
  db:
    image: mysql:5.7
    hostname: db-$BA_HOST_NAME.brandaddition.docker
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes: 
      - database:/var/lib/mysql
      # - ./docker/mysql:/docker-entrypoint-initdb.d
    networks: 
      - backend
  fpm:
    image: brandaddition/php:7.3-fpm
    hostname: fpm-$BA_HOST_NAME.brandaddition.docker
    depends_on: 
      - elasticsearch
      - rabbitmq
      - redis
      - mailhog
    env_file: 
      - ./.env
      - ./composer.env
    volumes: 
      - sock:/sock
      # - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/.vscode:/var/www/html/.vscode
      - workspace:/var/www/html
      - ./src/app:/var/www/html/app
      - ./src/composer.json:/var/www/html/composer.json
      - ./src/composer.lock:/var/www/html/composer.lock
      - $COMPOSER_CACHE:/var/www/.composer/cache
    ports: 
      - 3000:3000
      - 3001:3001
    networks:
      - backend

  web:
    image: brandaddition/nginx:1.17
    hostname: web-$BA_HOST_NAME.brandaddition.docker
    links:
      - fpm
    depends_on: 
      - fpm
    ports: 
      - 80:80
      - 443:443
    volumes:
      - workspace:/var/www/html
      - ./.docker/nginx/brandaddition.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/sites:/etc/nginx/conf.d/sites
      - sock:/sock
    networks: 
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: 
      - db
    links:
      - db
    ports: 
      - 8080:80
    environment: 
      - PMA_HOST=db
      - PMA_USER=magento
      - PMA_PASSWORD=magento
      - MYSQL_ROOT_PASSWORD=magento
    networks: 
      - backend
    
  rabbitmq:
    image: brandaddition/rabbitmq:3.8-management-alpine
    environment: 
      - RABBITMQ_MAGENTO_USERNAME=magento
      - RABBITMQ_MAGENTO_PASSWORD=magento
    ports:
        - 15672:15672
        - 5672:5672
    networks: 
        - backend
  
  redis: 
    image: redis:alpine
    ports: 
        - 6379:6379
    networks: 
        - backend

  elasticsearch:
    image: brandaddition/elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks: 
      - backend
      
  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025
    networks: 
      - backend

networks: 
  backend:
    driver: bridge

volumes: 
  sock:
  database:
    name: m2-database-${BA_HOST_NAME}-test
    driver: local
  workspace:
    driver: local
    name: m2-workspace-${BA_HOST_NAME}-test