staging.brandadditionweb.com:
  hostname: staging.brandadditionweb.com
  stage: staging
  deploy_path: /var/www/deployer
  user: root
  port: 2020
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

brandadditionweb.com:
  hostname: brandadditionweb.com
  stage: production
  deploy_path: /var/www/vhosts/brandaddition/clients
  user: root
  port: 2020
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no