<div class="admin__control-table-wrapper">
    <table class="admin__control-table">
        <thead>
            <tr>
                <th>Caption</th>
                <th>Label</th>
                <th>Mandatory</th>
                <th>Visible</th>
                <th>Coupon</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>LABEL 0</td>
                <td><input type="text" /></td>
                <td><input type="checkbox" /></td>
                <td><input type="checkbox" /></td>
                <td><input type="radio" /></td>
            </tr>
        </tbody>
    </table>
</div>